### PR TITLE
Fix CSRF and clean up

### PR DESCRIPTION
**Pull request by robertIngrum**
- Update ruby version
- Remove string interpolation where not needed
- Ignore provider state since it can cause a CSRF error with devise
- Pull access token from params in case it's already set (fix for double redirect bug with devise)

### CODE REVIEW

**Comment by robertIngrum** [comment]
Probably not ready to merge since I didn't update tests, but it might be a good reference in case someone runs into CSRF errors.

**Comment by le0pard** [comment]
Hello, thanks. Can you rebase from latest master?

**Comment by robertIngrum** [comment]
Should be good now.  And thanks for the heads up on the strings, that's good to know.

**Comment by le0pard** [comment]
Thanks!

**Pull request merged**
